### ISSUE TITLE
Some questions regarding setup

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [artf/cimice#3]
Can you give more details on how to use it? Questions that come to mind:

1. What does an endpoint look like, can "https://save/frames" be any url that can receive POST, like a "rec.php"? If so, why do I not receive anything there?
2. Is that script on a website within script tags or is it somewhere out of reach and somehow referenced from the main index.html/index.php?
3. How is movie data being stored and read?

**Comment by artf** [comment]
1. Sure, can be any server side script, cimice just stores data (Frames) inside a container (Movie) while the user moves around the mouse, but if you want to 'replay' those data you have to store them physically somewhere (eg. DB)
2. The website just uses cimice as an example
3. I show here the example https://github.com/artf/cimice#playing You just get you frames (an array of objects) and put them inside the player, then `player.play()`
