### ISSUE TITLE
Source for cimice.min.js

### ISSUE THREAD

**Issue by trehoffman** [artf/cimice#5]
I was looking through the cimice.min.js file and was wondering if there is an un-minified and more readable version somewhere that I can look at?  

Did you write this file from scratch or did you base it on something else?

Thanks!

**Comment by artf** [comment]
The source is here https://github.com/artf/cimice/tree/master/src

**Comment by trehoffman** [comment]
I realize now that I misread something and completely missed what I was actually looking at...

Thank you!
